{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# dataset mergeing and cleaning"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import random\n",
    "import pandas as pd\n",
    "from datetime import datetime as dt\n",
    "from datetime import timedelta\n",
    "import os\n",
    "import requests"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "admission =     pd.read_csv(r\"F:\\SchoolWork\\research\\Med-BERT\\datasets\\admissions.csv\")\n",
    "diagnoses_icd = pd.read_csv(r\"F:\\SchoolWork\\research\\Med-BERT/datasets/diagnoses_icd.csv\")\n",
    "drgcodes =      pd.read_csv(r\"F:\\SchoolWork/research/Med-BERT\\datasets\\drgcodes.csv\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Part 1, Data preparation\n",
    "## Step 1, map ICD-9 into ICD-10;\n",
    "truncate all diagnose code into 3 digits"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#mapping ICD-9 TO ICD-10\n",
    "gem_df = pd.read_csv(r\"F:\\SchoolWork\\research\\Med-BERT\\datasets\\icd9toicd10cmgem.csv\")\n",
    "# 显示文件前几行以了解数据结构\n",
    "print(gem_df.head())\n",
    "\n",
    "# 创建一个字典用于ICD-9到ICD-10的映射\n",
    "icd9_to_icd10 = dict(zip(gem_df['icd9cm'], gem_df['icd10cm']))\n",
    "\n",
    "# 测试映射\n",
    "icd9_code = '0010'  # 替换为你要映射的ICD-9代码\n",
    "icd10_code = icd9_to_icd10.get(icd9_code, 'MAPPING UNFOUND')\n",
    "\n",
    "print(f'ICD-9代码 {icd9_code} 对应的ICD-10代码是: {icd10_code}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "diagnoses_icd.loc[diagnoses_icd['icd_version'] == 9, 'icd_code'] = diagnoses_icd.loc[diagnoses_icd['icd_version'] == 9, 'icd_code'].apply(lambda x: icd9_to_icd10.get(x, 'MAPPING UNFOUND'))\n",
    "diagnoses_icd['icd_code'] = diagnoses_icd['icd_code'].str.slice(0, 3)\n",
    "diagnoses_icd.head(30)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "drgcodes.columns\n",
    "diagnoses_icd.columns\n",
    "#admission.columns"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## step 2, construct a file with index of hadm_list "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "hadm_list = pd.unique(admission['hadm_id'])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "data_diag is an array with columns of 'patient_sk','admit_dt_tm','discharge_dt_tm', 'third_party_ind','diagnosis',\n",
    "admission中的subject_id为patient_sk\n",
    "admission中的admittime为admit_dt_tm\n",
    "admission中的dischtime为discharge_dt_tm\n",
    "admission中的insurance为third_party_ind\n",
    "diagnoses_icd中的icd_code为diagnosis\n",
    "将admission['hadm_id']作为匹配索引，每行都有一个单独的diagnosis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'admission' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_26856\\811729331.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m admission.rename(columns={\n\u001b[0m\u001b[0;32m      2\u001b[0m     \u001b[1;34m'subject_id'\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;34m'patient_sk'\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m     \u001b[1;34m'admittime'\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;34m'admit_dt_tm'\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m     \u001b[1;34m'dischtime'\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;34m'discharge_dt_tm'\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m     \u001b[1;34m'insurance'\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;34m'third_party_ind'\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNameError\u001b[0m: name 'admission' is not defined"
     ]
    }
   ],
   "source": [
    "admission.rename(columns={\n",
    "    'subject_id': 'patient_sk',\n",
    "    'admittime': 'admit_dt_tm',\n",
    "    'dischtime': 'discharge_dt_tm',\n",
    "    'insurance': 'third_party_ind'\n",
    "}, inplace=True)\n",
    "\n",
    "diagnoses_icd.rename(columns={\n",
    "    'icd_code': 'diagnosis'\n",
    "}, inplace=True)\n",
    "\n",
    "# 将admission和diagnoses_icd数据集进行合并，按hadm_id进行匹配\n",
    "merged_data = pd.merge(admission, diagnoses_icd, on='hadm_id', how='left')\n",
    "\n",
    "# 保留需要的列\n",
    "final_data = merged_data[['patient_sk', 'admit_dt_tm', 'discharge_dt_tm', 'third_party_ind', 'diagnosis']]\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    " Convert time into ymd form"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "final_data['admit_dt_tm'] = final_data['admit_dt_tm'].apply(lambda x: dt.strptime(x, \"%Y-%m-%d %H:%M:%S\").strftime(\"%Y-%m-%d\"))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "final_data['discharge_dt_tm'] = final_data['discharge_dt_tm'].apply(lambda x: dt.strptime(x, \"%Y-%m-%d %H:%M:%S\").strftime(\"%Y-%m-%d\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# 保存到新的CSV文件\n",
    "final_data.to_csv('diagdatashort.csv', index=False)\n",
    "\n",
    "# 打印前几行以检查结果\n",
    "print(final_data.head())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# PART 2, DATA PREPROCESSING"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['patient_sk', 'admit_dt_tm', 'discharge_dt_tm', 'third_party_ind',\n",
       "       'diagnosis'],\n",
       "      dtype='object')"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pd.read_csv(r\"F:/SchoolWork/research/Med-BERT/Pretraining Code/Data Pre-processing Code\\diagdatashort.csv\").columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Data file\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py:13: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.\n",
      "  del sys.path[0]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sampling\n",
      "Start Data Preprocessing !!!\n",
      "Processed 1000 pts\n",
      "Splitting\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "sys.path.append(\"F:/SchoolWork/research/Med-BERT/Pretraining Code/Data Pre-processing Code\")\n",
    "from gpt_data_processing_code import main\n",
    "\n",
    "\n",
    "# 设置参数\n",
    "diagFile = r\"F:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\diagdatashort.csv\"\n",
    "typeFile = \"NA\"  # 如果没有类型文件，则设为 None\n",
    "outFile = \"dataprocessed\"\n",
    "p_samplesize = 1000  # 设置采样大小，如果不需要采样则设为 0\n",
    "\n",
    "# 调用 main 函数\n",
    "main(diagFile, typeFile, outFile, p_samplesize)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# PART 2.5, transforming the test, valid, train data into TFRecords"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pickle5 in c:\\users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages (0.0.12)\n"
     ]
    }
   ],
   "source": [
    "!pip3 install pickle5"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\n",
      "c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\n",
      "c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\n",
      "c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\n",
      "c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\n",
      "c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2\n",
      "2\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 0 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 3 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 1\n",
      "1\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 0 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 3 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 0\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 0 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 2 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 0\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 0 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 2 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 0\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 0 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 2 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 0\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 0 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 3 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 1\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 0 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 1 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 0\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 0 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 3 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 0\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 0 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 3 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 0\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 0 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 2 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 0\n",
      "9\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 3 3 0 0 3 3 3 3 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 2 3 4 5 6 7 8 9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 2 3 0\n",
      "INFO:tensorflow:masked_lm_ids: 3 3 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 1.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 1\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 3 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 2 3 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 3 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 2 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 1\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 0 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 3 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 0\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 0 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 3 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 0\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 0 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 2 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 0\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 3 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 1 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 3 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 0\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 2 2 2 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 2 3 4 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 3 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 2 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 0\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 1 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 2 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 0\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 3 3 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 2 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 3 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 0\n",
      "INFO:tensorflow:*** Example ***\n",
      "INFO:tensorflow:input_ids: 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:input_mask: 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:segment_ids: 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
      "INFO:tensorflow:masked_lm_positions: 0 0 0\n",
      "INFO:tensorflow:masked_lm_ids: 3 0 0\n",
      "INFO:tensorflow:masked_lm_weights: 1.0 0.0 0.0\n",
      "INFO:tensorflow:next_sentence_labels: 0\n",
      "31\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([11531307, [3, 14], [460, 0], [3, 3], [1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([11076634, [1], [0], [3], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([15394964, [1], [0], [2], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([14438817, [7], [0], [2], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([14809055, [3], [0], [2], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([13055132, [12], [0], [3], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([18568644, [0], [0], [1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([19135348, [1], [0], [3], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([13586070, [0], [0], [3], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([18437199, [0], [0], [2], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([19699040, [6, 6, 4, 4, 1, 1, 2, 2, 10], [1936, 47, 22, 586, 87, 790, 538, 125, 0], [3, 3, 3, 3, 3, 3, 3, 3, 3], [1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([19466242, [12, 2, 1, 19], [937, 1618, 0, 0], [3, 2, 2, 2], [1, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([15886237, [1], [0], [3], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([10530907, [6], [0], [3], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([19337113, [3], [0], [2], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([14253880, [3, 4], [17, 0], [3, 3], [1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([14664283, [0, 7, 1, 1, 3], [0, 453, 67, 0, 0], [2, 2, 2, 2, 2], [1, 2, 3, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([13318898, [2, 4], [0, 0], [2, 2], [1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([11115360, [5, 0, 1], [539, 517, 0], [3, 3, 3], [1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 608, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\logging\\__init__.py\", line 369, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 387, in do_execute\n",
      "    cell_id=cell_id,\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures, cell_id\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3029, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3472, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3552, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_22020\\2061742649.py\", line 7, in <module>\n",
      "    prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 23, in preprocess_data\n",
      "    write_EHRinstance_to_example_files(train_data, max_seq_length, max_predictions_per_seq, masked_lm_prob, vocab, output_files, rng)\n",
      "  File \"f:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\gpt_data_prep.py\", line 101, in write_EHRinstance_to_example_files\n",
      "    tf.logging.info(\"tokens: \" , seq)\n",
      "  File \"c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\platform\\tf_logging.py\", line 156, in info\n",
      "    get_logger().info(msg, *args, **kwargs)\n",
      "Message: 'tokens: '\n",
      "Arguments: ([10838202, [3, 2], [99, 0], [3, 3], [1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Wrote 2099 total instances\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "sys.path.append(\"F:/SchoolWork/research/Med-BERT/Pretraining Code/Data Pre-processing Code\")\n",
    "import gpt_data_prep as prep\n",
    "input_file0 = \"F:/SchoolWork/research/Med-BERT/Pretraining Code/Data Pre-processing Code/dataprocessed.bencs.train\"\n",
    "output_file = 'F:/SchoolWork/research\\Med-BERT/Pretraining Code/Data Pre-processing Code/prepared/outputtrain.tfrecord'\n",
    "vocab_file = 'F:/SchoolWork/research/Med-BERT/Pretraining Code/Data Pre-processing Code/dataprocessed.types'\n",
    "prep.preprocess_data(input_file0, output_file, vocab_file, max_seq_length=32, max_predictions_per_seq=2, masked_lm_prob=0.2, random_seed=12345)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Part 3, running the pre-training model\n",
    "\n",
    "## Step 1, running the pretraining Med-Bert for Pretraining"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "sys.path.append(\"F:/SchoolWork/research/Med-BERT/Pretraining Code\")\n",
    "#from gptQA2Seq import main_function   #where we make sure that LOS classification task is using the full sequence rather than the first token"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "input_file = r\"F:/SchoolWork/research/Med-BERT/Pretraining Code/Data Pre-processing Code/dataprocessed.bencs.train,F:/SchoolWork/research/Med-BERT/Pretraining Code/Data Pre-processing Code/dataprocessed.bencs.valid, F:/SchoolWork/research/Med-BERT/Pretraining Code/Data Pre-processing Code/dataprocessed.bencs.test\"\n",
    "bert_config_file = r\"F:/SchoolWork/research/Med-BERT/Pretraining Code/config.json\"\n",
    "output_dir = r\"F:/SchoolWork/research/Med-BERT/Pretraining Code/BertQA2Seq\"\n",
    "\n",
    "#main_function(input_files, bert_config_file, output_dir)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:*** Input Files ***\n",
      "INFO:tensorflow:  F:\\SchoolWork\\research\\Med-BERT\\Pretraining Code\\Data Pre-processing Code\\prepared\\outputtrain.tfrecord\n",
      "\n",
      "WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.\n",
      "For more information, please see:\n",
      "  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md\n",
      "  * https://github.com/tensorflow/addons\n",
      "If you depend on functionality not listed there, please file an issue.\n",
      "\n",
      "WARNING:tensorflow:Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x000001ED3AE2E798>) includes params argument, but params are not passed to Estimator.\n",
      "INFO:tensorflow:Using config: {'_model_dir': 'F:/SchoolWork/research/Med-BERT/Pretraining Code/Bertmodel', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true\n",
      "graph_options {\n",
      "  rewrite_options {\n",
      "    meta_optimizer_iterations: ONE\n",
      "  }\n",
      "}\n",
      ", '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001ED3BA744C8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None), '_cluster': None}\n",
      "INFO:tensorflow:_TPUContext: eval_on_tpu True\n",
      "WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.\n",
      "INFO:tensorflow:***** Running training *****\n",
      "INFO:tensorflow:  Batch size = 32\n",
      "INFO:tensorflow:***** Running evaluation *****\n",
      "INFO:tensorflow:  Batch size = 8\n",
      "INFO:tensorflow:Not using Distribute Coordinator.\n",
      "INFO:tensorflow:Running training and evaluation locally (non-distributed).\n",
      "INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps 1000 or save_checkpoints_secs None.\n",
      "WARNING:tensorflow:From c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Colocations handled automatically by placer.\n",
      "WARNING:tensorflow:From F:/SchoolWork/research/Med-BERT/Pretraining Code\\gptpretraining.py:383: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use `tf.data.experimental.parallel_interleave(...)`.\n",
      "WARNING:tensorflow:From F:/SchoolWork/research/Med-BERT/Pretraining Code\\gptpretraining.py:400: map_and_batch (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use `tf.data.experimental.map_and_batch(...)`.\n",
      "WARNING:tensorflow:From F:/SchoolWork/research/Med-BERT/Pretraining Code\\gptpretraining.py:415: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use tf.cast instead.\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Running train on CPU\n",
      "INFO:tensorflow:*** Features ***\n",
      "INFO:tensorflow:  name = input_ids, shape = (32, 128)\n",
      "INFO:tensorflow:  name = input_mask, shape = (32, 128)\n",
      "INFO:tensorflow:  name = masked_lm_ids, shape = (32, 20)\n",
      "INFO:tensorflow:  name = masked_lm_positions, shape = (32, 20)\n",
      "INFO:tensorflow:  name = masked_lm_weights, shape = (32, 20)\n",
      "INFO:tensorflow:  name = next_sentence_labels, shape = (32, 1)\n",
      "INFO:tensorflow:  name = segment_ids, shape = (32, 128)\n",
      "WARNING:tensorflow:From F:/SchoolWork/research/Med-BERT/Pretraining Code\\modeling.py:358: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.\n",
      "WARNING:tensorflow:From F:/SchoolWork/research/Med-BERT/Pretraining Code\\modeling.py:671: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use keras.layers.dense instead.\n",
      "INFO:tensorflow:**** Trainable Variables ****\n",
      "INFO:tensorflow:  name = bert/embeddings/word_embeddings:0, shape = (82603, 192)\n",
      "INFO:tensorflow:  name = bert/embeddings/token_type_embeddings:0, shape = (1000, 192)\n",
      "INFO:tensorflow:  name = bert/embeddings/position_embeddings:0, shape = (512, 192)\n",
      "INFO:tensorflow:  name = bert/embeddings/LayerNorm/beta:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/embeddings/LayerNorm/gamma:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_0/attention/self/query/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_0/attention/self/query/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_0/attention/self/key/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_0/attention/self/key/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_0/attention/self/value/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_0/attention/self/value/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_0/attention/output/dense/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_0/attention/output/dense/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_0/attention/output/LayerNorm/beta:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_0/attention/output/LayerNorm/gamma:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_0/intermediate/dense/kernel:0, shape = (192, 64)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_0/intermediate/dense/bias:0, shape = (64,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_0/output/dense/kernel:0, shape = (64, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_0/output/dense/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_0/output/LayerNorm/beta:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_0/output/LayerNorm/gamma:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_1/attention/self/query/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_1/attention/self/query/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_1/attention/self/key/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_1/attention/self/key/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_1/attention/self/value/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_1/attention/self/value/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_1/attention/output/dense/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_1/attention/output/dense/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_1/attention/output/LayerNorm/beta:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_1/attention/output/LayerNorm/gamma:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_1/intermediate/dense/kernel:0, shape = (192, 64)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_1/intermediate/dense/bias:0, shape = (64,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_1/output/dense/kernel:0, shape = (64, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_1/output/dense/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_1/output/LayerNorm/beta:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_1/output/LayerNorm/gamma:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_2/attention/self/query/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_2/attention/self/query/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_2/attention/self/key/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_2/attention/self/key/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_2/attention/self/value/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_2/attention/self/value/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_2/attention/output/dense/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_2/attention/output/dense/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_2/attention/output/LayerNorm/beta:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_2/attention/output/LayerNorm/gamma:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_2/intermediate/dense/kernel:0, shape = (192, 64)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_2/intermediate/dense/bias:0, shape = (64,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_2/output/dense/kernel:0, shape = (64, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_2/output/dense/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_2/output/LayerNorm/beta:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_2/output/LayerNorm/gamma:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_3/attention/self/query/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_3/attention/self/query/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_3/attention/self/key/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_3/attention/self/key/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_3/attention/self/value/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_3/attention/self/value/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_3/attention/output/dense/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_3/attention/output/dense/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_3/attention/output/LayerNorm/beta:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_3/attention/output/LayerNorm/gamma:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_3/intermediate/dense/kernel:0, shape = (192, 64)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_3/intermediate/dense/bias:0, shape = (64,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_3/output/dense/kernel:0, shape = (64, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_3/output/dense/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_3/output/LayerNorm/beta:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_3/output/LayerNorm/gamma:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_4/attention/self/query/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_4/attention/self/query/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_4/attention/self/key/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_4/attention/self/key/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_4/attention/self/value/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_4/attention/self/value/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_4/attention/output/dense/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_4/attention/output/dense/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_4/attention/output/LayerNorm/beta:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_4/attention/output/LayerNorm/gamma:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_4/intermediate/dense/kernel:0, shape = (192, 64)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_4/intermediate/dense/bias:0, shape = (64,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_4/output/dense/kernel:0, shape = (64, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_4/output/dense/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_4/output/LayerNorm/beta:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_4/output/LayerNorm/gamma:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_5/attention/self/query/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_5/attention/self/query/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_5/attention/self/key/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_5/attention/self/key/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_5/attention/self/value/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_5/attention/self/value/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_5/attention/output/dense/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_5/attention/output/dense/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_5/attention/output/LayerNorm/beta:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_5/attention/output/LayerNorm/gamma:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_5/intermediate/dense/kernel:0, shape = (192, 64)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_5/intermediate/dense/bias:0, shape = (64,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_5/output/dense/kernel:0, shape = (64, 192)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_5/output/dense/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_5/output/LayerNorm/beta:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/encoder/layer_5/output/LayerNorm/gamma:0, shape = (192,)\n",
      "INFO:tensorflow:  name = bert/pooler/dense/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = bert/pooler/dense/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = cls/predictions/transform/dense/kernel:0, shape = (192, 192)\n",
      "INFO:tensorflow:  name = cls/predictions/transform/dense/bias:0, shape = (192,)\n",
      "INFO:tensorflow:  name = cls/predictions/transform/LayerNorm/beta:0, shape = (192,)\n",
      "INFO:tensorflow:  name = cls/predictions/transform/LayerNorm/gamma:0, shape = (192,)\n",
      "INFO:tensorflow:  name = cls/predictions/output_bias:0, shape = (82603,)\n",
      "INFO:tensorflow:  name = cls/seq_relationship/output_weights:0, shape = (2, 192)\n",
      "INFO:tensorflow:  name = cls/seq_relationship/output_bias:0, shape = (2,)\n",
      "WARNING:tensorflow:From c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\training\\learning_rate_decay_v2.py:321: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Deprecated in favor of operator or tf.math.divide.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "WARNING:tensorflow:From c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\training\\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use standard file APIs to check for files with this prefix.\n",
      "INFO:tensorflow:Restoring parameters from F:/SchoolWork/research/Med-BERT/Pretraining Code/Bertmodel\\model.ckpt-0\n",
      "WARNING:tensorflow:From c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\training\\saver.py:1070: get_checkpoint_mtimes (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use standard file utilities to get mtimes.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into F:/SchoolWork/research/Med-BERT/Pretraining Code/Bertmodel\\model.ckpt.\n",
      "INFO:tensorflow:Error recorded from training_loop: Key: masked_lm_positions.  Can't parse serialized Example.\n",
      "\t [[{{node ParseSingleExample/ParseSingleExample}}]]\n",
      "\t [[node IteratorGetNext (defined at c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\util.py:110) ]]\n",
      "INFO:tensorflow:training_loop marked as finished\n",
      "WARNING:tensorflow:Reraising captured error\n"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "Key: masked_lm_positions.  Can't parse serialized Example.\n\t [[{{node ParseSingleExample/ParseSingleExample}}]]\n\t [[node IteratorGetNext (defined at c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\util.py:110) ]]",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_do_call\u001b[1;34m(self, fn, *args)\u001b[0m\n\u001b[0;32m   1333\u001b[0m     \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1334\u001b[1;33m       \u001b[1;32mreturn\u001b[0m \u001b[0mfn\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1335\u001b[0m     \u001b[1;32mexcept\u001b[0m \u001b[0merrors\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mOpError\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_run_fn\u001b[1;34m(feed_dict, fetch_list, target_list, options, run_metadata)\u001b[0m\n\u001b[0;32m   1318\u001b[0m       return self._call_tf_sessionrun(\n\u001b[1;32m-> 1319\u001b[1;33m           options, feed_dict, fetch_list, target_list, run_metadata)\n\u001b[0m\u001b[0;32m   1320\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_call_tf_sessionrun\u001b[1;34m(self, options, feed_dict, fetch_list, target_list, run_metadata)\u001b[0m\n\u001b[0;32m   1406\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_session\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0moptions\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfeed_dict\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfetch_list\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtarget_list\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1407\u001b[1;33m         run_metadata)\n\u001b[0m\u001b[0;32m   1408\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mInvalidArgumentError\u001b[0m: Key: masked_lm_positions.  Can't parse serialized Example.\n\t [[{{node ParseSingleExample/ParseSingleExample}}]]\n\t [[{{node IteratorGetNext}}]]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_22020\\1221829026.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      7\u001b[0m \u001b[0mbert_config_file\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mos\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpath\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mjoin\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"F:/SchoolWork/research/Med-BERT/Pretraining Code/config.json\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      8\u001b[0m \u001b[0moutput_dir\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mos\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpath\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mjoin\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"F:/SchoolWork/research/Med-BERT/Pretraining Code/Bertmodel\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 9\u001b[1;33m \u001b[0mgptpretraining\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mmain\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mbert_config_file\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0minput_file\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0moutput_dir\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32mF:/SchoolWork/research/Med-BERT/Pretraining Code\\gptpretraining.py\u001b[0m in \u001b[0;36mmain\u001b[1;34m(bert_config_file, input_file, output_dir, do_train, do_eval, use_tpu, tpu_name, tpu_zone, gcp_project, master, save_checkpoints_steps, iterations_per_loop, num_tpu_cores, train_batch_size, eval_batch_size, init_checkpoint, learning_rate, num_train_steps, num_warmup_steps, max_seq_length, max_predictions_per_seq)\u001b[0m\n\u001b[0;32m    490\u001b[0m         \u001b[0mtrain_spec\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mestimator\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mTrainSpec\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0minput_fn\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mtrain_input_fn\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mmax_steps\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mnum_train_steps\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    491\u001b[0m         \u001b[0meval_spec\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mestimator\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mEvalSpec\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0minput_fn\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0meval_input_fn\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mthrottle_secs\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 492\u001b[1;33m         \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mestimator\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtrain_and_evaluate\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mestimator\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtrain_spec\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0meval_spec\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    493\u001b[0m         \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mresult\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    494\u001b[0m         \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mresult\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\training.py\u001b[0m in \u001b[0;36mtrain_and_evaluate\u001b[1;34m(estimator, train_spec, eval_spec)\u001b[0m\n\u001b[0;32m    469\u001b[0m         '(with task id 0).  Given task id {}'.format(config.task_id))\n\u001b[0;32m    470\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 471\u001b[1;33m   \u001b[1;32mreturn\u001b[0m \u001b[0mexecutor\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    472\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    473\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\training.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    609\u001b[0m         config.task_type != run_config_lib.TaskType.EVALUATOR):\n\u001b[0;32m    610\u001b[0m       \u001b[0mlogging\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0minfo\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'Running training and evaluation locally (non-distributed).'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 611\u001b[1;33m       \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrun_local\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    612\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    613\u001b[0m     \u001b[1;31m# Distributed case.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\training.py\u001b[0m in \u001b[0;36mrun_local\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    710\u001b[0m         \u001b[0mmax_steps\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_train_spec\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mmax_steps\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    711\u001b[0m         \u001b[0mhooks\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mtrain_hooks\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 712\u001b[1;33m         saving_listeners=saving_listeners)\n\u001b[0m\u001b[0;32m    713\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    714\u001b[0m     eval_result = listener_for_eval.eval_result or _EvalResult(\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\contrib\\tpu\\python\\tpu\\tpu_estimator.py\u001b[0m in \u001b[0;36mtrain\u001b[1;34m(self, input_fn, hooks, steps, max_steps, saving_listeners)\u001b[0m\n\u001b[0;32m   2455\u001b[0m     \u001b[1;32mfinally\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2456\u001b[0m       \u001b[0mrendezvous\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrecord_done\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'training_loop'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 2457\u001b[1;33m       \u001b[0mrendezvous\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mraise_errors\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   2458\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2459\u001b[0m   def evaluate(self,\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\contrib\\tpu\\python\\tpu\\error_handling.py\u001b[0m in \u001b[0;36mraise_errors\u001b[1;34m(self, timeout_sec)\u001b[0m\n\u001b[0;32m    126\u001b[0m       \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    127\u001b[0m         \u001b[0mlogging\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mwarn\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'Reraising captured error'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 128\u001b[1;33m         \u001b[0msix\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mreraise\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtyp\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtraceback\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    129\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    130\u001b[0m     \u001b[1;32mfor\u001b[0m \u001b[0mk\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m(\u001b[0m\u001b[0mtyp\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtraceback\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mkept_errors\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\six.py\u001b[0m in \u001b[0;36mreraise\u001b[1;34m(tp, value, tb)\u001b[0m\n\u001b[0;32m    717\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__traceback__\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0mtb\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    718\u001b[0m                 \u001b[1;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtb\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 719\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    720\u001b[0m         \u001b[1;32mfinally\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    721\u001b[0m             \u001b[0mvalue\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\contrib\\tpu\\python\\tpu\\tpu_estimator.py\u001b[0m in \u001b[0;36mtrain\u001b[1;34m(self, input_fn, hooks, steps, max_steps, saving_listeners)\u001b[0m\n\u001b[0;32m   2450\u001b[0m           \u001b[0msteps\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0msteps\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2451\u001b[0m           \u001b[0mmax_steps\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mmax_steps\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 2452\u001b[1;33m           saving_listeners=saving_listeners)\n\u001b[0m\u001b[0;32m   2453\u001b[0m     \u001b[1;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[1;33m:\u001b[0m  \u001b[1;31m# pylint: disable=broad-except\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2454\u001b[0m       \u001b[0mrendezvous\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrecord_error\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'training_loop'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0msys\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mexc_info\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\estimator.py\u001b[0m in \u001b[0;36mtrain\u001b[1;34m(self, input_fn, hooks, steps, max_steps, saving_listeners)\u001b[0m\n\u001b[0;32m    356\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    357\u001b[0m       \u001b[0msaving_listeners\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0m_check_listeners_type\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msaving_listeners\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 358\u001b[1;33m       \u001b[0mloss\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_train_model\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0minput_fn\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mhooks\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0msaving_listeners\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    359\u001b[0m       \u001b[0mlogging\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0minfo\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'Loss for final step: %s.'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mloss\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    360\u001b[0m       \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\estimator.py\u001b[0m in \u001b[0;36m_train_model\u001b[1;34m(self, input_fn, hooks, saving_listeners)\u001b[0m\n\u001b[0;32m   1122\u001b[0m       \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_train_model_distributed\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0minput_fn\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mhooks\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0msaving_listeners\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1123\u001b[0m     \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1124\u001b[1;33m       \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_train_model_default\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0minput_fn\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mhooks\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0msaving_listeners\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1125\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1126\u001b[0m   \u001b[1;32mdef\u001b[0m \u001b[0m_train_model_default\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0minput_fn\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mhooks\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0msaving_listeners\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\estimator.py\u001b[0m in \u001b[0;36m_train_model_default\u001b[1;34m(self, input_fn, hooks, saving_listeners)\u001b[0m\n\u001b[0;32m   1156\u001b[0m       return self._train_with_estimator_spec(estimator_spec, worker_hooks,\n\u001b[0;32m   1157\u001b[0m                                              \u001b[0mhooks\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mglobal_step_tensor\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1158\u001b[1;33m                                              saving_listeners)\n\u001b[0m\u001b[0;32m   1159\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1160\u001b[0m   \u001b[1;32mdef\u001b[0m \u001b[0m_train_model_distributed\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0minput_fn\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mhooks\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0msaving_listeners\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\estimator.py\u001b[0m in \u001b[0;36m_train_with_estimator_spec\u001b[1;34m(self, estimator_spec, worker_hooks, hooks, global_step_tensor, saving_listeners)\u001b[0m\n\u001b[0;32m   1405\u001b[0m       \u001b[0many_step_done\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mFalse\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1406\u001b[0m       \u001b[1;32mwhile\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0mmon_sess\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mshould_stop\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1407\u001b[1;33m         \u001b[0m_\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mloss\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mmon_sess\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mestimator_spec\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtrain_op\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mestimator_spec\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mloss\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1408\u001b[0m         \u001b[0many_step_done\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mTrue\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1409\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0many_step_done\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(self, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m    674\u001b[0m                           \u001b[0mfeed_dict\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mfeed_dict\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    675\u001b[0m                           \u001b[0moptions\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0moptions\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 676\u001b[1;33m                           run_metadata=run_metadata)\n\u001b[0m\u001b[0;32m    677\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    678\u001b[0m   \u001b[1;32mdef\u001b[0m \u001b[0mrun_step_fn\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mstep_fn\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(self, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m   1169\u001b[0m                               \u001b[0mfeed_dict\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mfeed_dict\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1170\u001b[0m                               \u001b[0moptions\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0moptions\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1171\u001b[1;33m                               run_metadata=run_metadata)\n\u001b[0m\u001b[0;32m   1172\u001b[0m       \u001b[1;32mexcept\u001b[0m \u001b[0m_PREEMPTION_ERRORS\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1173\u001b[0m         logging.info('An error was raised. This may be due to a preemption in '\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m   1268\u001b[0m         \u001b[1;32mraise\u001b[0m \u001b[0msix\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mreraise\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0moriginal_exc_info\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1269\u001b[0m       \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1270\u001b[1;33m         \u001b[1;32mraise\u001b[0m \u001b[0msix\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mreraise\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0moriginal_exc_info\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1271\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1272\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\six.py\u001b[0m in \u001b[0;36mreraise\u001b[1;34m(tp, value, tb)\u001b[0m\n\u001b[0;32m    717\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__traceback__\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0mtb\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    718\u001b[0m                 \u001b[1;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtb\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 719\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    720\u001b[0m         \u001b[1;32mfinally\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    721\u001b[0m             \u001b[0mvalue\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m   1253\u001b[0m   \u001b[1;32mdef\u001b[0m \u001b[0mrun\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1254\u001b[0m     \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1255\u001b[1;33m       \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_sess\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1256\u001b[0m     \u001b[1;32mexcept\u001b[0m \u001b[0m_PREEMPTION_ERRORS\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1257\u001b[0m       \u001b[1;32mraise\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(self, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m   1325\u001b[0m                                   \u001b[0mfeed_dict\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mfeed_dict\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1326\u001b[0m                                   \u001b[0moptions\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0moptions\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1327\u001b[1;33m                                   run_metadata=run_metadata)\n\u001b[0m\u001b[0;32m   1328\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1329\u001b[0m     \u001b[1;32mfor\u001b[0m \u001b[0mhook\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_hooks\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m   1089\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1090\u001b[0m   \u001b[1;32mdef\u001b[0m \u001b[0mrun\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1091\u001b[1;33m     \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_sess\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1092\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1093\u001b[0m   \u001b[1;32mdef\u001b[0m \u001b[0mrun_step_fn\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mstep_fn\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mraw_session\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mrun_with_hooks\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(self, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m    927\u001b[0m     \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    928\u001b[0m       result = self._run(None, fetches, feed_dict, options_ptr,\n\u001b[1;32m--> 929\u001b[1;33m                          run_metadata_ptr)\n\u001b[0m\u001b[0;32m    930\u001b[0m       \u001b[1;32mif\u001b[0m \u001b[0mrun_metadata\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    931\u001b[0m         \u001b[0mproto_data\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtf_session\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mTF_GetBuffer\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mrun_metadata_ptr\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_run\u001b[1;34m(self, handle, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m   1150\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0mfinal_fetches\u001b[0m \u001b[1;32mor\u001b[0m \u001b[0mfinal_targets\u001b[0m \u001b[1;32mor\u001b[0m \u001b[1;33m(\u001b[0m\u001b[0mhandle\u001b[0m \u001b[1;32mand\u001b[0m \u001b[0mfeed_dict_tensor\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1151\u001b[0m       results = self._do_run(handle, final_targets, final_fetches,\n\u001b[1;32m-> 1152\u001b[1;33m                              feed_dict_tensor, options, run_metadata)\n\u001b[0m\u001b[0;32m   1153\u001b[0m     \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1154\u001b[0m       \u001b[0mresults\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m[\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_do_run\u001b[1;34m(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m   1326\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0mhandle\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1327\u001b[0m       return self._do_call(_run_fn, feeds, fetches, targets, options,\n\u001b[1;32m-> 1328\u001b[1;33m                            run_metadata)\n\u001b[0m\u001b[0;32m   1329\u001b[0m     \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1330\u001b[0m       \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_do_call\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0m_prun_fn\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mhandle\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfeeds\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfetches\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_do_call\u001b[1;34m(self, fn, *args)\u001b[0m\n\u001b[0;32m   1346\u001b[0m           \u001b[1;32mpass\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1347\u001b[0m       \u001b[0mmessage\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0merror_interpolation\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0minterpolate\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmessage\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_graph\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1348\u001b[1;33m       \u001b[1;32mraise\u001b[0m \u001b[0mtype\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0me\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mnode_def\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mop\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mmessage\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1349\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1350\u001b[0m   \u001b[1;32mdef\u001b[0m \u001b[0m_extend_graph\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mInvalidArgumentError\u001b[0m: Key: masked_lm_positions.  Can't parse serialized Example.\n\t [[{{node ParseSingleExample/ParseSingleExample}}]]\n\t [[node IteratorGetNext (defined at c:\\Users\\xitia\\anaconda3\\envs\\medbert_env\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\util.py:110) ]]"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "import tensorflow as tf\n",
    "import os\n",
    "sys.path.append(\"F:/SchoolWork/research/Med-BERT/Pretraining Code\")\n",
    "import gptpretraining\n",
    "input_file = \"F:/SchoolWork/research\\Med-BERT/Pretraining Code/Data Pre-processing Code/prepared/outputtrain.tfrecord\"\n",
    "bert_config_file = os.path.join(\"F:/SchoolWork/research/Med-BERT/Pretraining Code/config.json\")\n",
    "output_dir = os.path.join(\"F:/SchoolWork/research/Med-BERT/Pretraining Code/Bertmodel\")\n",
    "gptpretraining.main(bert_config_file, input_file, output_dir)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['F:\\\\SchoolWork\\\\research\\\\Med-BERT\\\\Pretraining Code\\\\Data Pre-processing Code\\\\dataprocessed.bencs.train', 'F:\\\\SchoolWork\\\\research\\\\Med-BERT\\\\Pretraining Code\\\\Data Pre-processing Code\\\\dataprocessed.bencs.valid', 'F:\\\\SchoolWork\\\\research\\\\Med-BERT\\\\Pretraining Code\\\\Data Pre-processing Code\\\\dataprocessed.bencs.test']\n",
      "WARNING:tensorflow:From C:\\Users\\xitia\\AppData\\Local\\Temp\\ipykernel_26856\\455312334.py:12: tf_record_iterator (from tensorflow.python.lib.io.tf_record) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use eager execution and: \n",
      "`tf.data.TFRecordDataset(path)`\n",
      "['F:\\\\SchoolWork\\\\research\\\\Med-BERT\\\\Pretraining Code\\\\Data Pre-processing Code\\\\dataprocessed.bencs.train', 'F:\\\\SchoolWork\\\\research\\\\Med-BERT\\\\Pretraining Code\\\\Data Pre-processing Code\\\\dataprocessed.bencs.valid', 'F:\\\\SchoolWork\\\\research\\\\Med-BERT\\\\Pretraining Code\\\\Data Pre-processing Code\\\\dataprocessed.bencs.test'] is not a TFRecord file.\n"
     ]
    }
   ],
   "source": [
    "input_file = \"F:/SchoolWork/research/Med-BERT/Pretraining Code/Data Pre-processing Code/dataprocessed.bencs.train,F:/SchoolWork/research/Med-BERT/Pretraining Code/Data Pre-processing Code/dataprocessed.bencs.valid,F:/SchoolWork/research/Med-BERT/Pretraining Code/Data Pre-processing Code/dataprocessed.bencs.test\"\n",
    "input_files=[]\n",
    "for input_pattern in input_file.split(\",\"):\n",
    "    input_files.extend(tf.gfile.Glob(input_pattern))\n",
    "print(input_files)\n",
    "\n",
    "import tensorflow as tf\n",
    "\n",
    "def is_tfrecord(filenames):\n",
    "  for filename in filenames:\n",
    "    try:\n",
    "        record_iterator = tf.compat.v1.io.tf_record_iterator(path=filename)\n",
    "        for string_record in record_iterator:\n",
    "            return True\n",
    "    except tf.errors.DataLossError:\n",
    "        return False\n",
    "\n",
    "# Replace 'your_file.tfrecord' with the path to your file\n",
    "file_path = input_files\n",
    "if is_tfrecord(file_path):\n",
    "    print(f\"{file_path} is a TFRecord file.\")\n",
    "else:\n",
    "    print(f\"{file_path} is not a TFRecord file.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "BERT_env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
